config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  namespace :api do
    namespace :v1 do
      post '/signin', to: 'sessions#create'

      get '/users/:user_id/keywords', to: 'keywords#index'
      post '/users/:user_id/keywords', to: 'keywords#create'
      get '/keywords/:id/search_result', to: 'search_results#show'
    end
  end

  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }

  authenticated :user do
    resources :keywords, only: %i[index show new create]
    get 'search', to: 'search#index'
  end

  unauthenticated do
    match '*path' => redirect('/users/sign_in'), via: %i[get post put patch delete]
  end

  root to: 'keywords#new'
end

app/models/keyword.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: keywords
#
#  id         :bigint           not null, primary key
#  name       :string           not null
#  status     :integer          default("pending")
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  user_id    :bigint           not null
#
# Indexes
#
#  index_keywords_on_name     (name)
#  index_keywords_on_status   (status)
#  index_keywords_on_user_id  (user_id)
#
# Foreign Keys
#
#  fk_rails_...  (user_id => users.id)
#
class Keyword < ApplicationRecord
  validates :name, presence: true

  belongs_to :user
  has_one :search_result, dependent: :destroy

  enum status: { pending: 3, processing: 2, success: 1, fail: 0 }
end

app/controllers/api/v1/keywords_controller.rb
# frozen_string_literal: true

module Api
  module V1
    # Handling API V1 Keywords routing logic
    class KeywordsController < BaseRestApiController
      def index
        render_jsonapi keyword_repository.find_all_by_user(current_user.id)
      end

      def create
        if can_attach_keyword_file?
          KeywordScrapingJob.perform_later(user_id: current_user.id,
                                           keyword_file_key: current_user.keyword_file.key)
          render json: { message: I18n.t('keywords.upload_csv_successfully') }, status: :accepted
        else
          render_json_api_error_response(error_msg: I18n.t('keywords.upload_csv_failed'))
        end
      end

      private

      def can_attach_keyword_file?
        keyword_params.present? && current_user.keyword_file.attach(keyword_params)
      end

      def keyword_params
        params.permit(:keyword_file)[:keyword_file]
      end

      def keyword_repository
        @keyword_repository ||= KeywordRepository.new
      end
    end
  end
end

app/controllers/keywords_controller.rb
# frozen_string_literal: true

# Handling Keywords routing logic
class KeywordsController < ApplicationController
  def index
    @keywords = keyword_repository.find_all_by_user(current_user.id)
  end

  def show
    @keyword = keyword_repository.find_by(id: params[:id], user_id: current_user.id)
  end

  def new; end

  def create
    file_handler_service = handle_file_keyword

    if file_handler_service.success?
      queue_keyword_scraping_jobs(file_handler_service.result)
      redirect_to keywords_path, notice: I18n.t('keywords.upload_csv_successfully')
    else
      redirect_to root_path, alert: file_handler_service.errors.full_messages.to_sentence
    end
  end

  private

  def keyword_params
    params.permit(:keyword_file)[:keyword_file]
  end

  def keyword_repository
    @keyword_repository ||= KeywordRepository.new
  end

  def handle_file_keyword
    FileKeywordHandlerService.call(user: current_user, file: keyword_params)
  end

  # NOTE: Extract to a separate service if logic gets more complex
  def queue_keyword_scraping_jobs(keyword_ids)
    keyword_ids.each do |keyword_id|
      KeywordScrapingJob.perform_later(keyword_id)
    end
  end
end

app/views/keywords/_headers.html.haml
%th Keyword
%th Status
%th Created At

app/views/keywords/_infor.html.haml
- if (local_assigns[:include_link] && keyword.status == 'success') || false
  %td= link_to(keyword.name, keyword_path(keyword))
- else
  %td= keyword.name

%td= keyword.status.humanize
%td= format_date(keyword.created_at)

app/views/keywords/_search_result_available.html.haml
.row
  .col-md-8.offset-md-2
    %h1= @keyword.name
    %table.table.table-striped
      - search_result = @keyword.search_result
      %thead
        %tr
          = render 'search_result_headers'
      %tbody
        %tr
          = render 'search_result_infor', search_result: search_result
.row
  .col-md-8.offset-md-2
    = link_to "Back to keywords", keywords_path, class: "btn btn-secondary"

app/views/keywords/_search_result_headers.html.haml
%th Total Number of AdWords
%th Total Number of Links
%th Total Search Results
%th HTML Source Code

app/views/keywords/_search_result_infor.html.haml
%td= search_result&.adwords_advertisers
%td= search_result&.total_links
%td= search_result&.total_search_results
%td= search_result&.html

app/views/keywords/_search_result_not_available.html.haml
.row
  %h1 Search result for this keyword is not available yet or the keyword scraping failed.
.row
  .col-md-2
    = link_to "Back to keywords", keywords_path, class: "btn btn-secondary"

app/views/keywords/index.html.haml
.row
  .col-md-8.offset-md-2
    %h1 My Uploaded Keywords
    %table.table.table-striped
      %thead
        %tr
          = render 'headers'
      %tbody
        - @keywords.each do |keyword|
          %tr{id: dom_id(keyword)}
            = render partial: 'infor', locals: { keyword: keyword, include_link: true }

.row
  .col-md-8.offset-md-2
    = link_to "Upload a new keyword file", new_keyword_path, class: "btn btn-primary"

app/views/keywords/new.html.haml
= form_with(url: keywords_path, local: true, method: :post, enctype: "multipart/form-data") do |form|
  .mb-3
    = form.label :keyword_file, class: "form-label"
    = form.file_field :keyword_file, class: "form-control", required: true

  .mb-3
    = form.submit "Upload", class: "btn btn-primary"

app/views/keywords/show.html.haml
- if @keyword.status == 'success'
  = render 'search_result_available', keyword: @keyword
- else
  = render 'search_result_not_available'