config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  namespace :api do
    namespace :v1 do
      post '/signin', to: 'sessions#create'

      get '/users/:user_id/keywords', to: 'keywords#index'
      post '/users/:user_id/keywords', to: 'keywords#create'
      get '/keywords/:id/search_result', to: 'search_results#show'
    end
  end

  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }

  authenticated :user do
    resources :keywords, only: %i[index show new create]
    get 'search', to: 'search#index'
  end

  unauthenticated do
    match '*path' => redirect('/users/sign_in'), via: %i[get post put patch delete]
  end

  root to: 'keywords#new'
end

app/views/layouts/_flash.html.haml
- flash.each do |name, msg|
  - if msg.is_a?(String)
    .alert{ class: "alert-#{name == 'alert' ? 'danger' : 'success'} alert-dismissible fade show", role: "alert" }
      %button{ type: "button", class: "btn-close", "data-bs-dismiss": "alert", "aria-label": "Close" }
      = msg

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title GoogleSearchExtractor
    %meta{:content => "width=device-width,initial-scale=1", :name => "viewport"}/
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag "application", "data-turbo-track": "reload"
    = javascript_include_tag "application", "data-turbo-track": "reload", defer: true
  %body
    .container-fluid
      %nav.navbar.navbar-expand-lg.navbar-light.bg-light
        %a.navbar-brand{ href: root_path} Google Search Extractor
        %button.navbar-toggler{ type: "button", "data-bs-toggle": "collapse", "data-bs-target": "#navbarNav", "aria-controls": "navbarNav", "aria-expanded": "false", "aria-label": "Toggle navigation" }
          %span.navbar-toggler-icon
        #navbarNav.collapse.navbar-collapse
          %ul.navbar-nav.ms-auto.mb-2.mb-lg-0
            - if user_signed_in?
              %li.nav-item
                = link_to "Uploaded Keywords", keywords_path, class: "nav-link"
              %li.nav-item
                = link_to "Search Across Report", search_path, class: "nav-link"
              %li.nav-link
                %span.navbar-text= username(current_user)
              %li.nav-item
                = link_to "Logout", destroy_user_session_path, method: :delete, class: "nav-link"
            - else
              %li.nav-item
                = link_to "Sign in", new_user_session_path, class: "nav-link"
              %li.nav-item
                = link_to "Sign up", new_user_registration_path, class: "nav-link"

      .container
        = render partial: 'layouts/flash'

      = yield